### ISSUE TITLE
chemrxiv api downtime

### ISSUE THREAD

**Issue by jannisborn** [cthoyt/chemrxiv-summarize#3]
HI @cthoyt, can you confirm that the chemrxiv api is down? https://api.figshare.com/v2/articles?institution=259 returns an empty list, but other institutions (e.g., 2, 5, 8) work fine. 

Regarding your particular package, running `python 01_download.py` now fails:
```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.figshare.com/v2/account/institution
```

I noticed that also the chemrxiv dashboard hasn't been updated since September 15: https://chemrxiv-dashboard.github.io

**Comment by cthoyt** [comment]
Hi @jannisborn, I can confirm this package is no longer functional. ChemRxiv switched from using the open FigShare platform to the closed Engage platform, and it's no longer possible to programmatically interact with it. I'm quite frustrated about this choice.

**Comment by jannisborn** [comment]
That is really a bummer! I'm maintaining a package to scrape publications from pubmed and all major x-rxiv servers (arxiv, biorxiv, medrxiv and chemrxiv). It's really a pity to see chemrxiv falling behind all the others in terms of functionalities for end users.

For anyone else seeing this and looking for further information: when chemrxiv was launched in 2017, figshare was choosen to power it ([see here](https://figshare.com/blog/Figshare_to_power_ChemRxiv_Beta_New_Chemistry_Preprint_Server_For_The_Global_Chemistry_Community/322)), but effectively summer 2021 chemrxiv was moved to open engage ([see here](https://axial.acs.org/2021/06/10/chemrxiv-open-engage-platform/)).

Quite ironic that it's called **Open** Engage...
Anyways. thanks for the quick response @cthoyt

**Comment by jannisborn** [comment]
Small update @cthoyt, just ICYMI: It seems that there will be a chemrxiv API from Engage: https://connect.acspubs.org/chemrxiv

**Comment by cthoyt** [comment]
I don't see any evidence of an API actually existing based on the text on that page. Only that they might have one, and it might get posted there in the future. Thanks for the reference, but I don't have a ton of confidence in this platform to be honest given that it's run by a publisher which is notorious for being conservative

**Comment by jannisborn** [comment]
I just found it: https://chemrxiv.org/engage/chemrxiv/public-api/v1/items 

But I havent found any documentation. The figshare guide was truly fantastic and I doubt we will get something comparable. But seeing this API accessible is a step forward.
